version: '3'

services:
  engine:
    build:
      context: ./
      dockerfile: ./engine/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - "./engine:/app"

  interface:
    build:
      context: ./
      dockerfile: ./interface/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - "./interface:/app"

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
