version: '3'

services:
  engine:
    build:
      context: ./
      dockerfile: ./engine/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - "./engine:/app"

  redis:
    image: redis:alpine
    # ports:
    #   - "6379:6379"
