version: '3'

services:
  engine:
    build:
      context: ./
      dockerfile: ./engine/Dockerfile
    ports:
      - "8200:8000"
    env_file:
      - stack.env
    volumes:
      - "engine:/app"

  interface:
    build:
      context: ./
      dockerfile: ./interface/Dockerfile
    ports:
      - "8201:8001"
    env_file:
      - stack.env
    volumes:
      - "interface:/app"

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
  engine:
  interface:
